# Generated by Django 3.1.1 on 2020-09-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_food_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='memo',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
