# Generated by Django 3.1.1 on 2020-09-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20200925_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='memo',
        ),
    ]
